#!/usr/bin/env bash
# Deploy the whole stack on this server, from source, and prove it answers.
#
# Run on the server, from the repository root, as the deploy user:
#
#   cd ~/MoraPay && git pull && infra/scripts/server-deploy.sh
#
# Safe to run repeatedly. It rebuilds, restarts, and re-checks; it does not
# touch the database beyond running migrations, so transfer history and the
# ledger survive a redeploy.
#
# On first run it writes .env with generated secrets. Those secrets are for a
# demonstration against simulated rails. Real ones come from a vault before
# anything approaching live funds (BUILD_PLAN 12.5, OPEN_ITEMS P3).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

COMPOSE="docker compose -f infra/compose/server.yml"
WEB_PORT="${WEB_PUBLIC_PORT:-80}"
ADMIN_PORT="${ADMIN_PUBLIC_PORT:-8080}"

# The address the browser will use. Detected, because the whole point of this
# file is that there is no domain yet; override when there is one, or when the
# server is behind NAT and its own view of its address is wrong.
PUBLIC_HOST="${PUBLIC_HOST:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')}"
if [ -z "$PUBLIC_HOST" ]; then
  echo "✗ Could not determine this server's public address. Set PUBLIC_HOST=<ip> and re-run." >&2
  exit 1
fi

# ------------------------------------------------------------------ secrets
if [ ! -f .env ]; then
  echo "→ first run: generating .env"
  command -v openssl >/dev/null 2>&1 || { echo "✗ openssl is required" >&2; exit 1; }
  gen() { openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-40; }

  cp .env.example .env
  {
    echo ""
    echo "# ---- generated by server-deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "POSTGRES_PASSWORD=$(gen)"
    echo "JWT_ACCESS_SECRET=$(gen)"
    echo "ADMIN_JWT_ACCESS_SECRET=$(gen)"
    echo "QUOTE_SIGNING_SECRET=$(gen)"
    echo "FIELD_ENCRYPTION_KEY=$(openssl rand -base64 32)"
    echo "TOKENISATION_SALT=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_RU_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_NG_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_GH_SIM=$(gen)"
    echo "NODE_ENV=production"
    echo "LIVE_FUNDS_ENABLED=false"
  } >> .env
  chmod 600 .env
  echo "   .env written, mode 600. It is gitignored; keep it that way."
fi

# The two origins are derived every run, so moving to a domain is one variable.
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-http://${PUBLIC_HOST}$([ "$WEB_PORT" = "80" ] || echo ":$WEB_PORT")}"
ADMIN_ORIGIN="${ADMIN_ORIGIN:-http://${PUBLIC_HOST}:${ADMIN_PORT}}"
export PUBLIC_ORIGIN ADMIN_ORIGIN WEB_PUBLIC_PORT="$WEB_PORT" ADMIN_PUBLIC_PORT="$ADMIN_PORT"
# shellcheck disable=SC2046
export POSTGRES_PASSWORD="$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2-)"

echo "→ building (a few minutes on the first run; layers are cached after that)"
$COMPOSE build

echo "→ migrating and seeding"
$COMPOSE run --rm migrate

echo "→ starting"
$COMPOSE up -d --remove-orphans

# --------------------------------------------------------------- verifying
wait_for() {
  local url="$1" want="${2:-200}" tries="${3:-90}"
  for _ in $(seq "$tries"); do
    [ "$(curl -s -o /dev/null -m 5 -w '%{http_code}' "$url" || echo 000)" = "$want" ] && return 0
    sleep 2
  done
  return 1
}

echo "→ verifying"
wait_for "http://localhost:${WEB_PORT}/login" || {
  echo "✗ the sender app did not come up" >&2; $COMPOSE logs --tail=30 web >&2; exit 1; }
wait_for "http://localhost:${ADMIN_PORT}/login" || {
  echo "✗ the back office did not come up" >&2; $COMPOSE logs --tail=30 admin >&2; exit 1; }

# The check that matters on a server with no domain: the front end must be able
# to reach the API through its own origin. If this fails the pages still render
# and every action fails, which is the confusing failure this whole arrangement
# exists to prevent.
for entry in "sender app:$WEB_PORT" "back office:$ADMIN_PORT"; do
  port="${entry##*:}"
  if curl -s -m 10 "http://localhost:${port}/api/health" | grep -q '"status"'; then
    echo "✓ ${entry%%:*} reaches the API through its own origin"
  else
    echo "✗ ${entry%%:*} cannot reach the API through /api" >&2
    $COMPOSE logs --tail=30 api >&2
    exit 1
  fi
done

if curl -s -m 10 "http://localhost:${WEB_PORT}/api/health/ledger" | grep -q '"balanced":true'; then
  echo "✓ ledger balanced"
else
  echo "✗ the ledger does not report itself balanced — do not demonstrate this" >&2
  exit 1
fi

cat <<EOF

  Sender app     ${PUBLIC_ORIGIN}
  Back office    ${ADMIN_ORIGIN}
  API health     ${PUBLIC_ORIGIN}/api/health

  Sender   chidi@demo.morapay.local / morapay-demo-2026
  Staff    compliance@morapay.local / morapay-local-staff-2026

  This is plain HTTP. Passwords cross the network in the clear and the browser
  will not install the app to a home screen, because a service worker needs a
  secure context. Acceptable for a demonstration against simulated rails with
  fictional senders; not acceptable for anything else. docs/DEPLOY_SERVER.md
  explains how to get a real certificate today, without owning a domain.

  Logs:    $COMPOSE logs -f api
  Stop:    $COMPOSE down
EOF
