#!/usr/bin/env bash
# Deploy the whole stack on this server, from source, and prove it answers.
#
# Run on the server, from the repository root, as the deploy user:
#
#   cd ~/MoraPay && git pull && infra/scripts/server-deploy.sh
#
# Safe to run repeatedly. It rebuilds, restarts, and re-checks; it does not
# touch the database beyond running migrations, so transfer history and the
# ledger survive a redeploy.
#
# On first run it writes .env with generated secrets. Those secrets are for a
# demonstration against simulated rails. Real ones come from a vault before
# anything approaching live funds (BUILD_PLAN 12.5, OPEN_ITEMS P3).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

COMPOSE="docker compose -f infra/compose/server.yml"
WEB_PORT="${WEB_PUBLIC_PORT:-80}"
ADMIN_PORT="${ADMIN_PUBLIC_PORT:-8080}"

# ---------------------------------------------------------------------- TLS
#
# Opt in with TLS=1. Without a domain, sslip.io resolves any IP-shaped name to
# that IP — including a prefixed one — so the two names needed here already
# point at this server and Let's Encrypt can validate them over HTTP-01.
#
# This is worth doing before anyone is shown the application. Over plain HTTP
# the browser will not register a service worker at all, so the PWA cannot
# install and the offline shell cannot be tested — and passwords cross the
# network in the clear.
TLS="${TLS:-0}"
if [ "$TLS" = "1" ]; then
  PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-}"
  ADMIN_HOSTNAME="${ADMIN_HOSTNAME:-}"
  # Filled in below, once the address is known.
  COMPOSE="$COMPOSE --profile tls"
  # The front ends move off the public interface; Caddy is the only listener.
  export WEB_BIND=127.0.0.1 ADMIN_BIND=127.0.0.1
  WEB_PORT=3000
  ADMIN_PORT=3001
fi

# The address the browser will use. Detected, because the whole point of this
# file is that there is no domain yet; override when there is one, or when the
# server is behind NAT and its own view of its address is wrong.
PUBLIC_HOST="${PUBLIC_HOST:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')}"
if [ -z "$PUBLIC_HOST" ]; then
  echo "✗ Could not determine this server's public address. Set PUBLIC_HOST=<ip> and re-run." >&2
  exit 1
fi

# ------------------------------------------------------------------ secrets
if [ ! -f .env ]; then
  echo "→ first run: generating .env"
  command -v openssl >/dev/null 2>&1 || { echo "✗ openssl is required" >&2; exit 1; }
  gen() { openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-40; }

  cp .env.example .env
  {
    echo ""
    echo "# ---- generated by server-deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "POSTGRES_PASSWORD=$(gen)"
    echo "JWT_ACCESS_SECRET=$(gen)"
    echo "ADMIN_JWT_ACCESS_SECRET=$(gen)"
    echo "QUOTE_SIGNING_SECRET=$(gen)"
    echo "FIELD_ENCRYPTION_KEY=$(openssl rand -base64 32)"
    echo "TOKENISATION_SALT=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_RU_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_NG_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_GH_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_NG_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_GH_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_CM_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYIN_BJ_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_ZA_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_CM_SIM=$(gen)"
    echo "PROVIDER_SIGNING_SECRET_PAYOUT_BJ_SIM=$(gen)"
    echo "NODE_ENV=production"
    echo "LIVE_FUNDS_ENABLED=false"
    echo ""
    echo "# This is a demonstration server, so the seeded staff and sender"
    echo "# accounts — whose passwords are published in docs/DEMO.md — are"
    echo "# wanted here despite NODE_ENV=production. Saying so explicitly is"
    echo "# what lets the seed run; the seed refuses outright if"
    echo "# LIVE_FUNDS_ENABLED is ever true, and that has no override."
    echo "#"
    echo "# Delete this line before this database is used for anything real."
    echo "ALLOW_DEMONSTRATION_SEED=true"
  } >> .env
  chmod 600 .env
  echo "   .env written, mode 600. It is gitignored; keep it that way."
fi

# The two origins are derived every run, so moving to a domain is one variable.
if [ "$TLS" = "1" ]; then
  # Default to sslip.io names for this server's address. Override both when a
  # real domain exists — nothing else in the deployment needs to change.
  PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-${PUBLIC_HOST}.sslip.io}"
  ADMIN_HOSTNAME="${ADMIN_HOSTNAME:-admin.${PUBLIC_HOST}.sslip.io}"
  PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-https://${PUBLIC_HOSTNAME}}"
  ADMIN_ORIGIN="${ADMIN_ORIGIN:-https://${ADMIN_HOSTNAME}}"
  export PUBLIC_HOSTNAME ADMIN_HOSTNAME ACME_EMAIL="${ACME_EMAIL:-}" \
    CADDY_ACME_CA="${CADDY_ACME_CA:-https://acme-v02.api.letsencrypt.org/directory}"
else
  PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-http://${PUBLIC_HOST}$([ "$WEB_PORT" = "80" ] || echo ":$WEB_PORT")}"
  ADMIN_ORIGIN="${ADMIN_ORIGIN:-http://${PUBLIC_HOST}:${ADMIN_PORT}}"
fi
export PUBLIC_ORIGIN ADMIN_ORIGIN WEB_PUBLIC_PORT="$WEB_PORT" ADMIN_PUBLIC_PORT="$ADMIN_PORT"
# shellcheck disable=SC2046
export POSTGRES_PASSWORD="$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2-)"

echo "→ building (a few minutes on the first run; layers are cached after that)"
$COMPOSE build

echo "→ migrating and seeding"
$COMPOSE run --rm migrate

echo "→ starting"
$COMPOSE up -d --remove-orphans

# --------------------------------------------------------------- verifying
wait_for() {
  local url="$1" want="${2:-200}" tries="${3:-90}"
  for _ in $(seq "$tries"); do
    [ "$(curl -s -o /dev/null -m 5 -w '%{http_code}' "$url" || echo 000)" = "$want" ] && return 0
    sleep 2
  done
  return 1
}

echo "→ verifying"
wait_for "http://localhost:${WEB_PORT}/login" || {
  echo "✗ the sender app did not come up" >&2; $COMPOSE logs --tail=30 web >&2; exit 1; }
wait_for "http://localhost:${ADMIN_PORT}/login" || {
  echo "✗ the back office did not come up" >&2; $COMPOSE logs --tail=30 admin >&2; exit 1; }

# The check that matters on a server with no domain: the front end must be able
# to reach the API through its own origin. If this fails the pages still render
# and every action fails, which is the confusing failure this whole arrangement
# exists to prevent.
#
# It retries, because the front ends answer well before the API finishes
# booting — Nest maps every route and connects to PostgreSQL first, which takes
# a few seconds longer than serving a login page. Asking once, immediately
# after the front ends come up, reports a healthy stack as broken.
wait_for_body() {
  local url="$1" needle="$2" tries="${3:-60}"
  for _ in $(seq "$tries"); do
    curl -s -m 5 "$url" 2>/dev/null | grep -q "$needle" && return 0
    sleep 2
  done
  return 1
}

for entry in "sender app:$WEB_PORT" "back office:$ADMIN_PORT"; do
  port="${entry##*:}"
  if wait_for_body "http://localhost:${port}/api/health" '"status"'; then
    echo "✓ ${entry%%:*} reaches the API through its own origin"
  else
    echo "✗ ${entry%%:*} cannot reach the API through /api" >&2
    $COMPOSE logs --tail=30 api >&2
    exit 1
  fi
done

if wait_for_body "http://localhost:${WEB_PORT}/api/health/ledger" '"balanced":true' 30; then
  echo "✓ ledger balanced"
else
  echo "✗ the ledger does not report itself balanced — do not demonstrate this" >&2
  exit 1
fi

if [ "$TLS" = "1" ]; then
  # Caddy fetches certificates on first request to each name, so the first load
  # is slow and can fail while ACME is still working. Wait for the real thing
  # rather than printing a URL that is not ready yet.
  echo "→ waiting for certificates (first issuance takes up to a minute)"
  for name in "$PUBLIC_HOSTNAME" "$ADMIN_HOSTNAME"; do
    ok=0
    for _ in $(seq 45); do
      if curl -sS -o /dev/null -m 8 "https://${name}/login" 2>/dev/null; then ok=1; break; fi
      sleep 2
    done
    if [ "$ok" = "1" ]; then
      echo "✓ https://${name} serving with a trusted certificate"
    else
      echo "✗ https://${name} did not come up." >&2
      echo "  Check that ports 80 and 443 are open in ufw and in the Hetzner" >&2
      echo "  firewall — Let's Encrypt validates over port 80, so a redirect" >&2
      echo "  is not enough, it has to reach Caddy." >&2
      $COMPOSE logs --tail=25 caddy >&2
      exit 1
    fi
  done
fi

cat <<EOF

  Sender app     ${PUBLIC_ORIGIN}
  Back office    ${ADMIN_ORIGIN}
  API health     ${PUBLIC_ORIGIN}/api/health

  Sender   chidi@demo.morapay.local / morapay-demo-2026
  Staff    compliance@morapay.local / morapay-local-staff-2026
EOF

if [ "$TLS" = "1" ]; then
  cat <<EOF

  Served over HTTPS with a Let's Encrypt certificate, renewed automatically.
  The app can now be installed to a home screen and the offline shell works.

  The hostname contains the IP, so it changes if the server does — right for a
  demonstration, wrong for a pilot. Point a real domain here and re-run with
  PUBLIC_HOSTNAME and ADMIN_HOSTNAME set; nothing else changes.
EOF
else
  cat <<EOF

  This is plain HTTP. Passwords cross the network in the clear and the browser
  will not install the app to a home screen, because a service worker needs a
  secure context. Acceptable for a demonstration against simulated rails with
  fictional senders; not acceptable for anything else.

  For a real certificate today, without owning a domain:
      TLS=1 infra/scripts/server-deploy.sh
EOF
fi

cat <<EOF

  Logs:    $COMPOSE logs -f api
  Stop:    $COMPOSE down
EOF
